### ISSUE TITLE
Usar cookies

### ISSUE THREAD

**Issue by Jose-Jaime-Castaneda** [Jose-Jaime-Castaneda/adogtame-3-frontend#1]
Cambiar el uso de localStorage a Cookies usando js-cookie, con la finalidad de cambiar los componentes de cliente a componententes del servidor, ya que localStorage solo funciona en el servidor.

**Comment by Erick-Hernandez-Ortega** [comment]
### Resuelto

- Se instalo la libreria js-cookie
- Se hizo la modificacion necesaria en el login para guardar el user en cookies
- Se adapto en la vista de profile
